name: hw1_env
dependencies:
  - python=3.8.*
  - pip
  - pip:
    - ipython
    - jupyter
    - jupyterlab
    - matplotlib==3.4.*
    - numpy
    - scikit-learn
    - scipy
    - pandas
    - statsmodels
    - seaborn
    - xgboost
    - shap
    - pickleshare

